apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev
  labels:
    lesson: "3"
    task: "3"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
  labels:
    lesson: "3"
    task: "3"
