apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    lesson: "3"
    task: "2"
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
