kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-rolebinding
subjects:
- kind: Group
  name: prometheus
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
