apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: default
  labels:
    lesson: "3"
    task: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: default
  labels:
    lesson: "3"
    task: "1"