apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
  labels:
    lesson: "3"
    task: "1"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: block
  labels:
    lesson: "3"
    task: "1"
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]

