apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bob
  namespace: default
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ['']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dave
  namespace: default
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "false"
    rbac.authorization.k8s.io/aggregate-to-edit: "false"
    rbac.authorization.k8s.io/aggregate-to-view: "false"

rules:
  - apiGroups: ['']
    resources: ['']
    verbs: ['']
