apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bob
  namespace: default
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dave
  namespace: default
rules:
  - apiGroups: ['']
    resources: ['']
    verbs: ['']
