kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: bob
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: block-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: dave
roleRef:
  kind: ClusterRole
  name: block
  apiGroup: rbac.authorization.k8s.io
